ALTER TABLE animais
    ADD COLUMN IF NOT EXISTS idade VARCHAR(20),
    ADD COLUMN IF NOT EXISTS faixa_etaria VARCHAR(100),
    ADD COLUMN IF NOT EXISTS responsavel VARCHAR(150),
    ADD COLUMN IF NOT EXISTS contato VARCHAR(50);
